Melodic devel local planner unittests and cleanup
robomechanics/quad-software pull request #201
Opened 2022-02-18 23:40 UTC by ardalantj

-- Removed convex MPC stuff, global planner, and other external packages that arent used
-- Implemented unit tests for footstep planner
-- Fixed the issue of local planner throwing when getting outside the map

2022-02-19 20:03 UTC, jcnorby requested changes

2022-02-20 15:58 UTC, ardalantj commented on nmpc_controller/nmpc_controller.yaml
> +    state_weights: [5.0, 5.0, 5.0, 0.5, 2.5, 2.5, 0.1, 0.1, 0.2, 0.05, 0.05, 0.01]
Was trying to resolve the pitching issue, but it doesnt happen anymore so will revert.

2022-02-20 16:10 UTC, jcnorby commented on quad_utils/launch/planning.launch
>          <node name="nmpc_controller" pkg="nmpc_controller" type="nmpc_controller_node" output="screen"/>
Try this:
```
<launch>
  
    <include file="$(find quad_utils)/launch/load_params.launch" />

    <arg name="global_planner" default="twist"/>
    <arg name="local_planner" default="full"/>
    <arg name="logging" default="false"/>

    <!-- Launch the node to publish the global body plan -->
    <group if="$(eval arg('global_planner') == 'fgmp')">
        <node name="global_body_planner" pkg="global_body_planner" type="global_body_planner_node" output="screen" />
    </group>

    <!-- Use twist input to local plan and no global plan -->
    <group if="$(eval arg('global_planner') == 'twist')">
        <param name="local_planner/use_twist_input" value="true"/>
    </group>

    <node name="local_planner" pkg="local_planner" type="local_planner_node" output="screen"/>

    <group if="$(arg logging)">
        <include file="$(find quad_utils)/launch/logging.launch"/>
    </group>

</launch>
```

2022-02-20 16:18 UTC, jcnorby approved these changes

2022-02-20 16:29 UTC, merged